name: ❓ Question
description: Report your question here
title: "[Question]: "
labels: ["question❓️"]

body:
  - type: textarea
    id: description
    attributes:
        label: "📋 Description"
        description: A clear and concise description of the question.
    validations:
        required: true

  - type: input
    id: phfit_version
    attributes:
        label: "🔖 pHfit Version"
        description: "Specify the pHfit version you are using. You can find this information in the `phfit -v` command."
        placeholder: "e.g., vX.X.X"
    validations:
        required: false

  - type: textarea
    id: environment
    attributes:
        label: "🔍 Environment"
        description: |
            Optional: The environment information.
            Example:
            OS: WSL (Ubuntu 22.04)
        value: |
            OS:
        render: markdown
    validations:
        required: false

  - type: textarea
    id: anything_else
    attributes:
        label: "📎 Anything else?"
        description: |
            Optional: Add any other contexts, links, or screenshots about the question here.
    validations:
        required: false
